apiVersion: v1
kind: Service
metadata:
  labels:
    emt.service: {{ .Values.emtangular.service }}
  name: {{ .Values.emtangular.service }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 4200
  selector:
    emt.service: {{ .Values.emtangular.service }}
