apiVersion: v1
kind: Service
metadata:
  labels:
    emt.service: {{ .Values.emtswagger.service }}
  name: {{ .Values.emtswagger.service }}
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    emt.service: {{ .Values.emtswagger.service }}
